-- AI Chat / Task Intake cloud-function support schema
-- MySQL 8.0+
-- Scope derived from the provided LoginService + ChatService requirements.
-- This schema is for cloud-service authentication/chat support only.
-- Smart Task Board business tables (tasks, task_inputs, ai_extraction_records, etc.)
-- remain in the existing primary application database and should not be duplicated here.

SET NAMES utf8mb4;
SET time_zone = '+08:00';

-- 1) Cloud-service users authenticated by mobile phone.
CREATE TABLE IF NOT EXISTS cloud_users (
    user_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT 'Cloud service user ID',
    phone VARCHAR(32) NOT NULL COMMENT 'Mobile phone number, normalized by LoginService',
    status ENUM('active', 'disabled') NOT NULL DEFAULT 'active',
    last_login_at DATETIME(3) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (user_id),
    UNIQUE KEY uk_cloud_users_phone (phone),
    KEY idx_cloud_users_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='LoginService users';

-- 2) SMS verification requests.
-- Never store the verification code in plaintext. Store only a one-way digest.
CREATE TABLE IF NOT EXISTS sms_verification_codes (
    sms_code_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    phone VARCHAR(32) NOT NULL,
    purpose ENUM('login') NOT NULL DEFAULT 'login',
    code_hash CHAR(64) NOT NULL COMMENT 'SHA-256/HMAC digest; never plaintext code',
    provider_request_id VARCHAR(128) NULL COMMENT 'Aliyun number-auth/SMS request identifier',
    provider_biz_id VARCHAR(128) NULL,
    send_status ENUM('pending', 'sent', 'failed') NOT NULL DEFAULT 'pending',
    verify_status ENUM('pending', 'verified', 'expired', 'locked') NOT NULL DEFAULT 'pending',
    attempt_count SMALLINT UNSIGNED NOT NULL DEFAULT 0,
    max_attempts SMALLINT UNSIGNED NOT NULL DEFAULT 5,
    expires_at DATETIME(3) NOT NULL,
    verified_at DATETIME(3) NULL,
    client_ip VARCHAR(64) NULL,
    user_agent VARCHAR(512) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (sms_code_id),
    KEY idx_sms_phone_created (phone, created_at DESC),
    KEY idx_sms_phone_status (phone, verify_status, expires_at),
    KEY idx_sms_provider_request (provider_request_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='LoginService SMS verification lifecycle';

-- 3) JWT/session audit and revocation support.
-- JWT itself does not need to be persisted. Store only jti and lifecycle metadata.
CREATE TABLE IF NOT EXISTS login_sessions (
    session_id CHAR(36) NOT NULL COMMENT 'UUID generated by LoginService',
    user_id BIGINT UNSIGNED NOT NULL,
    jwt_jti CHAR(36) NOT NULL COMMENT 'JWT ID for revocation/audit',
    issued_at DATETIME(3) NOT NULL,
    expires_at DATETIME(3) NOT NULL,
    revoked_at DATETIME(3) NULL,
    revoke_reason VARCHAR(255) NULL,
    client_ip VARCHAR(64) NULL,
    user_agent VARCHAR(512) NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (session_id),
    UNIQUE KEY uk_login_sessions_jti (jwt_jti),
    KEY idx_login_sessions_user (user_id, created_at DESC),
    KEY idx_login_sessions_expiry (expires_at),
    CONSTRAINT fk_login_sessions_user
        FOREIGN KEY (user_id) REFERENCES cloud_users(user_id)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='JWT session audit/revocation metadata';

-- 4) Chat / task-intake conversation container.
-- scene allows the same ChatService to support general chat and task-field clarification.
CREATE TABLE IF NOT EXISTS chat_sessions (
    chat_session_id CHAR(36) NOT NULL COMMENT 'UUID generated by ChatService',
    user_id BIGINT UNSIGNED NULL COMMENT 'Optional cloud login user',
    external_user_key VARCHAR(128) NULL COMMENT 'Optional task-board employee_no or external identity',
    scene ENUM('general_chat', 'task_field_extraction', 'task_field_clarification') NOT NULL DEFAULT 'general_chat',
    status ENUM('active', 'completed', 'cancelled') NOT NULL DEFAULT 'active',
    model_name VARCHAR(128) NULL,
    metadata_json JSON NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
    PRIMARY KEY (chat_session_id),
    KEY idx_chat_sessions_user (user_id, created_at DESC),
    KEY idx_chat_sessions_external_user (external_user_key, created_at DESC),
    KEY idx_chat_sessions_scene_status (scene, status),
    CONSTRAINT fk_chat_sessions_user
        FOREIGN KEY (user_id) REFERENCES cloud_users(user_id)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='ChatService conversation/session container';

-- 5) Conversation messages.
CREATE TABLE IF NOT EXISTS chat_messages (
    chat_message_id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    chat_session_id CHAR(36) NOT NULL,
    role ENUM('system', 'user', 'assistant', 'tool') NOT NULL,
    content MEDIUMTEXT NOT NULL,
    structured_json JSON NULL COMMENT 'Optional structured task-field extraction result',
    model_name VARCHAR(128) NULL,
    prompt_tokens INT UNSIGNED NULL,
    completion_tokens INT UNSIGNED NULL,
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    PRIMARY KEY (chat_message_id),
    KEY idx_chat_messages_session_time (chat_session_id, created_at, chat_message_id),
    CONSTRAINT fk_chat_messages_session
        FOREIGN KEY (chat_session_id) REFERENCES chat_sessions(chat_session_id)
        ON UPDATE CASCADE ON DELETE CASCADE
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='ChatService message history';

-- 6) LLM invocation observability. Avoid persisting API keys or Authorization headers.
CREATE TABLE IF NOT EXISTS llm_request_logs (
    llm_request_id CHAR(36) NOT NULL COMMENT 'UUID generated by ChatService',
    chat_session_id CHAR(36) NULL,
    provider VARCHAR(64) NOT NULL DEFAULT 'qwen',
    model_name VARCHAR(128) NOT NULL,
    request_type ENUM('chat', 'task_field_extraction', 'task_field_clarification') NOT NULL DEFAULT 'chat',
    status ENUM('pending', 'succeeded', 'failed') NOT NULL DEFAULT 'pending',
    http_status SMALLINT UNSIGNED NULL,
    latency_ms INT UNSIGNED NULL,
    prompt_tokens INT UNSIGNED NULL,
    completion_tokens INT UNSIGNED NULL,
    error_code VARCHAR(128) NULL,
    error_message VARCHAR(1000) NULL COMMENT 'Sanitized error text only',
    created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    completed_at DATETIME(3) NULL,
    PRIMARY KEY (llm_request_id),
    KEY idx_llm_logs_session (chat_session_id, created_at DESC),
    KEY idx_llm_logs_status_time (status, created_at DESC),
    KEY idx_llm_logs_provider_model (provider, model_name, created_at DESC),
    CONSTRAINT fk_llm_logs_session
        FOREIGN KEY (chat_session_id) REFERENCES chat_sessions(chat_session_id)
        ON UPDATE CASCADE ON DELETE SET NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci
  COMMENT='ChatService Qwen/LLM request audit and observability';
